blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('write/', views.blog_write, name='blog_write'),
    path('write/comment/<int:pk>/', views.blog_comment, name='blog_comment'),
    path('write/comment/reply/<int:pk>/', views.blog_comment_reply, name='blog_comment_reply'),
    path('delete/comment/<int:pk>/', views.blog_delete_comment, name='blog_delete_comment'),
    path('delete/recomment/<int:pk>/', views.blog_delete_recomment, name='blog_delete_recomment'),
    path('edit/<int:pk>/', views.blog_edit, name='blog_edit'),
    path('delete/<int:pk>/', views.blog_delete, name='blog_delete'),
    path('search/', views.blog_search, name='blog_search')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

travelog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   # path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.user_profile, name='user_profile'),
    path('delete/<int:pk>/', views.user_delete, name='user_delete'),
    path('profile/update/<int:pk>/', views.user_update, name='user_profile_update'),
    path('profile/change-password/', views.user_change_password, name='user_change_password'),
    path('profile/password_change_done', views.user_change_password_done, name='user_password_change_done')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

home = TemplateView.as_view(
    template_name = 'home/home.html'
)

templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travelog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <style rel="stylesheet">
        @font-face {
            font-family: 'Pretendard-Regular';
            src: url('https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff') format('woff');
            font-weight: 400;
            font-style: normal;
        }

        @keyframes backgroundChange {
            0% {
                background-position: 0 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }
        
        body {
            font-family: Pretendard-Regular;
            background-size: 150% 150%;
            background-repeat: no-repeat;
            animation: backgroundChange 20s ease-in-out infinite;
            background-image: url('{% static 'images/main-bg-cloud.jpg' %}');
        }

        a {
            text-decoration-line: none;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container-sm text-center justify-content-center" style="height: 100vh; display: flex; flex-direction: column;">
        <div class="row justify-content-center">
                <div class="row fs-1" style="height: 150px; color: wheat;">
                    <h1>Travelog</h1>
                </div>
                <div class="col col-sm-4 gap-5">
                    <div class="row justify-content-center">
                        <a class="btn btn-outline-light mb-3" href="{% url 'blog:blog_list' %}">시작하기</a>
                    </div>
                    {% if user.is_authenticated %}
                    <div class="row gap-5">
                        <a class="btn btn-outline-light mb-3" href="{% url 'user:user_logout' %}">로그아웃</a>
                    </div>
                    {% else %}
                    <div class="row">
                        <a class="btn btn-outline-light mb-3" href="{% url 'user:user_register' %}">회원가입</a>
                    </div>
                    <div class="row">
                        <a class="btn btn-outline-light" href="{% url 'user:user_login' %}">로그인</a>
                    </div>
                    {% endif %}
                </div>
                
        </div>
    </div>
</body>
</html>