blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('write/', views.blog_write, name='blog_write'),
    path('write/comment/<int:pk>/', views.blog_comment, name='blog_comment'),
    path('write/comment/reply/<int:pk>/', views.blog_comment_reply, name='blog_comment_reply'),
    path('delete/comment/<int:pk>/', views.blog_delete_comment, name='blog_delete_comment'),
    path('delete/recomment/<int:pk>/', views.blog_delete_recomment, name='blog_delete_recomment'),
    path('edit/<int:pk>/', views.blog_edit, name='blog_edit'),
    path('delete/<int:pk>/', views.blog_delete, name='blog_delete'),
    path('search/', views.blog_search, name='blog_search')
]

travelog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   # path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from collections.abc import Iterable
from django.db import models
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse

class Post(models.Model):
    title = models.CharField('제목', max_length=100)
    # body = models.TextField('내용')
    body = RichTextUploadingField('본문', blank=False, null=False, help_text='파일첨부는 이미지만 지원합니다. 본문내 이미지는 끌어다가 올리거나, 툴바에서 올릴 수 있습니다. 이미지가 너무 크지 않게 조절 해주세요 (추천 사이즈 512)')
    thumbnail_image = models.ImageField(
        '썸네일', upload_to='images/%Y/%m/%d/', blank=True, null=True
    )
    category = models.ForeignKey(
        'Category', on_delete=models.CASCADE, verbose_name='카테고리', 
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    tags = models.ManyToManyField(
        'Tag', blank=True
    )
    views_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_previous(self):
        return self.get_previous_by_created_at()
    
    def get_next(self):
        return self.get_next_by_created_at()
    
class Category(models.Model):
    type = models.CharField(max_length=10)

    def __str__(self):
        return self.type

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments',
    )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )    

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.message
    
class ReplyComment(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replys'
    )
    reply_message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.reply_message
    
    class Meta:
        ordering = ['-created_at']

blog/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import Post, Comment, ReplyComment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'thumbnail_image', 'category']

        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': '제목을 입력하세요...',
                'class': 'form-control'
            }),
            'thumbnail_image': forms.FileInput(attrs={
                'class': 'form-control'
            }),
            'category': forms.Select(attrs={
                'class': 'form-select',
            },),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

        widgets = {
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'style': 'height: 6rem; resize: none;',
                'placeholder': '댓글을 입력하세요',
            })
        }

class ReplyCommentForm(forms.ModelForm):
    class Meta:
        model = ReplyComment
        fields = ['reply_message']

        widgets = {
            'reply_message': forms.Textarea(attrs={
                'class': 'form-control',
                'style': 'height: 6rem; resize: none;',
                'placeholder': '',
            })
        }

blog/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Tag, Comment, ReplyComment
from .forms import PostForm, CommentForm, ReplyCommentForm
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class BlogListView(ListView):
    model = Post
    context_object_name = 'posts'
    ordering = '-created_at'
    paginate_by = 9

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        posts = context['posts']
        for post in posts:
            total = 0
            for comment in post.comments.all():
                total += len(comment.replys.all())
            total += len(post.comments.all())
            setattr(post, 'reply_count', total)

        return context

    
class BlogDetailView(DetailView):
    model = Post
    context_object_name = 'post'

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        pk = object.pk
        post = Post.objects.get(pk=pk)
        post.views_count += 1
        post.save()
        return super().get_object(queryset)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['commentForm'] = CommentForm()
        context['recommentForm'] = ReplyCommentForm()
        return context
    
    
class BlogWriteView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_write.html'

    def form_valid(self, form: BaseModelForm):
        postForm = form.save(commit=False)
        postForm.author = self.request.user
        response = super().form_valid(form)

        tags = self.request.POST.get('tag')
        if tags:
            tags = tags.split(',')
            for tag in tags:
                tag = tag.strip()
                _tag, _ = Tag.objects.get_or_create(name=tag)
                if _:
                    _tag.slug = slugify(tag, allow_unicode=True)
                    _tag.save()
                self.object.tags.add(_tag)

        return response

    def get_success_url(self):
        # return super().get_success_url()
        return reverse('blog:blog_detail', args=[str(self.object.pk)])

class BlogEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_write.html'
    redirect_unauthenticated_users = True

    def test_func(self) -> bool | None:
        return self.get_object().author == self.request.user
    
    def get_context_data(self, **kwargs):
        # return super().get_context_data(**kwargs)
        context = super().get_context_data(**kwargs)
        if self.object.tags.all():
            tag_list = []
            for t in self.object.tags.all():
                tag_list.append(t.name)
            context['tag_default'] = ', '.join(tag_list)

        return context
    
    def form_valid(self, form: BaseModelForm):
        response = super().form_valid(form)
        self.object.tags.clear()

        tags = self.request.POST.get('tag')
        if tags:
            tags = tags.split(',')
            for tag in tags:
                tag = tag.strip()
                _tag, _ = Tag.objects.get_or_create(name=tag)
                if _:
                    _tag.slug = slugify(tag, allow_unicode=True)
                    _tag.save()
                self.object.tags.add(_tag)

        return response

    def get_success_url(self):
        # return super().get_success_url()
        return reverse('blog:blog_detail', args=[str(self.object.pk)])
    
class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:blog_list')
    redirect_unauthenticated_users = True

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def test_func(self) -> bool | None:
        return self.get_object().author == self.request.user
    
class BlogCommentView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CommentForm
    template_name = None

    def form_valid(self, form: BaseModelForm):
        commentForm = form.save(commit=False)
        commentForm.post = self.get_object()
        commentForm.author = self.request.user
        commentForm.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('blog:blog_detail', args=[str(self.get_object().pk)])
    
class BlogCommentReplyView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = ReplyCommentForm
    template_name = None

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        recommentForm = form.save(commit=False)
        recommentForm.author = self.request.user
        recommentForm.comment = self.get_object()
        recommentForm.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('blog:blog_detail', args=[str(self.get_object().post.pk)])


class BlogCommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
    
    def test_func(self) -> bool | None:
        return self.get_object().author == self.request.user
    
    def get_success_url(self):
        return reverse('blog:blog_detail', args=[str(self.get_object().post.pk)])
    
class BlogReplyCommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ReplyComment

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
    
    def test_func(self) -> bool | None:
        return self.get_object().author == self.request.user
    
    def get_success_url(self):
        return reverse('blog:blog_detail', args=[str(self.get_object().comment.post.pk)])

class BlogSearchView(ListView):
    model = Post
    template_name = 'blog/post_search.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
            context = super().get_context_data(**kwargs)
            posts = context['posts']
            for post in posts:
                total = 0
                for comment in post.comments.all():
                    total += len(comment.replys.all())
                total += len(post.comments.all())
                setattr(post, 'reply_count', total)

            return context

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q', '')

        if q:
            queryset = queryset.distinct().filter(
                Q(title__icontains=q) | Q(category__type__iexact=q) | Q(tags__name__iexact=q)
            )
        else:
            queryset = queryset.none()

        return queryset

    def get_ordering(self):
        ordering = self.request.GET.get('sort', '')
        if ordering == 'latest':
            return '-created_at'
        elif ordering == 'past':
            return 'created_at'
        


blog_list = BlogListView.as_view()
blog_detail = BlogDetailView.as_view()
blog_write = BlogWriteView.as_view()
blog_edit = BlogEditView.as_view()
blog_delete = BlogDeleteView.as_view()
blog_search = BlogSearchView.as_view()
blog_comment = BlogCommentView.as_view()
blog_comment_reply = BlogCommentReplyView.as_view()
blog_delete_comment = BlogCommentDeleteView.as_view()
blog_delete_recomment = BlogReplyCommentDeleteView.as_view()

templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시물 삭제</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h1>게시물 삭제</h1>
        <p>정말로 삭제하시겠어요?</p>
        <button type="submit">네</button>
    </form>
    <button id="go-back">아니요</button>

    <script>
        document.getElementById('go-back').addEventListener("click", () => {
            window.history.back();
        });
    </script>
</body>
</html>

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block contents %}

<style rel="stylesheet">
    @media screen and (max-width: 768px) {
        p {
            font-size: 1rem !important;
        }
    }

    p {
        font-size: 1.125rem;
    }

    img, .thumbnail_image {
        max-height: 100vh;
        max-width: 100%;
        width: auto;
        margin: 0rem auto 0px;
        height: auto;
        object-fit: contain;
        display: block;
    }

    .thumbnail_image {
        margin: 2rem auto 0px;
    }

</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col col-md-7 g-5 pt-3">
            <h1 style="margin: 0 0 auto;">{{ post.title }}</h1>
            <p class="d-flex justify-content-between fs-6 align-items-center" style="margin-top: 2rem;">{{ post.author.nickname }} · {{ post.updated_at|date:"Y년 m월 d일" }}
                {% if user == post.author %}
                <span class="col-auto text-muted">
                    <a href="{% url 'blog:blog_edit' post.pk %}"><button class="btn btn-link-light">수정</button></a>
                    <button type="submit" class="btn btn-link-light" style="text-decoration: none; padding: 8px 8px 8px 8px" onclick="delete_confirm(this)" value="{% url 'blog:blog_delete' post.pk %}">삭제</button>
                </span>
                {% endif %}
            </p>
            
            {% for tag in post.tags.all %}
                <span class="fs-6"><a href="{% url 'blog:blog_search' %}?q={{tag}}&sort=latest" class="btn btn-outline-primary rounded-pill" style="padding: 0 16px; margin-bottom: 0.5rem; margin-right: 0.5rem;">#{{ tag }}</a></span>
            {% endfor %}

        
            {% if post.thumbnail_image %}
                <p><img class="thumbnail_image" src='{{ post.thumbnail_image.url }}'></p>
            {% endif %}
        
            <p style="margin-top: 32px;" class="ck-body fs-6">{{ post.body|safe }}</p>
            <hr>
            <div class="container mt-2 mb-2">
                <div class="row justify-content-between">
                    <div class="d-flex col-auto p-0 flex-row">
                        {% if post.get_previous %}
                        <a href="{% url 'blog:blog_detail' post.get_previous.pk %}" class="d-flex flex-row pe-4">
                            <div class="align-self-center">
                                ← 
                            </div>
                            <div class="d-flex flex-column ms-2 text-start">
                                <div style="font-size: 0.85rem;">이전글</div>
                                <div style="font-size: 1rem;">{{ post.get_previous.title }}</div>
                            </div>
                        </a>
                        {% endif %}
                    </div>
                    <div class="d-flex col-auto p-0 flex-row">
                        {% if post.get_next %}
                        <a href="{% url 'blog:blog_detail' post.get_next.pk %}" class="d-flex flex-row ps-4">
                            <div class="d-flex flex-column me-2 text-end">
                                <div style="font-size: 0.85rem;">다음글</div>
                                <div style="font-size: 1rem;">{{ post.get_next.title }}</div>
                            </div>
                            <div class="align-self-center">
                                → 
                            </div>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="container mt-4 mb-5">
                <div class="row">
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">목록으로</a>
                </div>
            </div>

            <form action="{% url 'blog:blog_comment' post.pk %}" method="POST">
                {% csrf_token %}
                <div class="container mt-4 mb-5">
                    <div class="row">
                        <div class="col-12 p-0">
                            {{ commentForm.message }}
                        </div>
                        <div class="col-12 p-0 text-end mt-3">
                            <button type="submit" class="btn btn-outline-primary">댓글 달기</button>
                        </div>
                    </div>
                </div>
            </form>

            <div class="container mb-5">
                {% for comment in post.comments.all %}
                <div class="row">

                        <div style="border-left: 3px solid #000;">
                            <div class="d-flex col-12 flex-row justify-content-between" style="font-size: 1.1rem;">
                                <div class="align-self-center"><b>{{ comment.author.nickname }}</b></div>
                                {% if user == comment.author %}
                                <button type="submit" class="btn btn-link-light" style="text-decoration: none;" value="{% url 'blog:blog_delete_comment' comment.pk %}" onclick="delete_confirm(this)">삭제</button>
                                {% endif %}
                            </div>
                            <div class="col-12" style="font-size: 0.9rem;">
                                {{ comment.created_at|date:'Y년 m월 d일 G:i' }}
                            </div>
                            <br>
                            <div class="col-12 mt-4">
                                {{ comment.message }}
                            </div>
                            <div class="col-12 mt-3 mb-1">
                                <button id="text_comment_btn_{{ comment.pk }}" class="btn btn-link p-0" style="text-decoration: none; color: #6c757d;" onclick="replyComment({{ comment.pk }})">댓글 달기</button>
                            </div>
                        </div>
                        
                        {% for recomment in comment.replys.all %}
                            <div class="container mt-3">
                                <div class="row">
                                    <div class="col-2 align-self-center">
                                        <!-- <img src="{% static './assets/reply_image.svg' %}"> -->
                                    </div>
                                    <div class="col-10" style="border-left: 3px solid #000;">
                                        <div class="d-flex col flex-row justify-content-between" style="font-size: 1.1rem;">
                                            <div class="align-self-center"><b>{{ recomment.author.nickname }}</b></div>
                                            {% if user == recomment.author %}
                                            <button type="submit" class="btn btn-link-light" style="text-decoration: none;" value="{% url 'blog:blog_delete_recomment' recomment.pk %}" onclick="delete_confirm(this)">삭제</button>
                                            {% endif %}
                                        </div>
                                        <div class="col" style="font-size: 0.9rem;">
                                            {{ recomment.created_at|date:'Y년 m월 d일 G:i' }}
                                        </div>
                                        <br>
                                        <div class="col">
                                            {{ recomment.reply_message }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        <div class="col-12 mt-3 mb-1" id="text_{{ comment.pk }}"  style="display: none;" >
                            <form action="{% url 'blog:blog_comment_reply' comment.pk %}" method="post">
                                {% csrf_token %}
                                <div class="container p-0">
                                    <div class="d-flex rol flex-column">
                                        <div class="col">
                                            {{ recommentForm.reply_message }}
                                        </div>
                                        <div class="col text-end">
                                            <button type="submit" class="btn btn-outline-secondary mt-2">댓글 달기</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-12">
                            <hr>
                        </div>
                    
                </div>
                {% endfor %}
            </div>

        
            
        </div>
    </div>

</div>

<script>
    function delete_confirm(obj) {
        if(confirm("정말 삭제하시겠습니까?") == true) {
            const form = document.createElement('form');
            form.setAttribute('method', 'POST');
            form.setAttribute('action', obj.value);
            
            const csrf_token = document.createElement('div');
            csrf_token.innerHTML = '{% csrf_token %}';
            
            form.appendChild(csrf_token);
            document.body.appendChild(form);
            form.submit();
        } else {
            return false;
        }
    }

    function replyComment(pk) {
        const replyForm = document.getElementById('text_'+pk)
        const replyBtn = document.getElementById('text_comment_btn_'+pk)
        console.log(' ', replyForm.style.display)
        if (replyForm.style.display == "none") {
            replyForm.setAttribute('style', 'display:block;')
            replyBtn.innerHTML = "접기"
        } else {
            replyForm.setAttribute('style', 'display:none;')
            replyBtn.innerHTML = "댓글 달기"
        }
        
    }
</script>

{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
<script type="text/javascript">
    window.onpageshow = function(event) {
        if ( event.persisted || (window.performance && window.performance.navigation.type == 2)) {
            // Back Forward Cache로 브라우저가 로딩될 경우 혹은 브라우저 뒤로가기 했을 경우
            // 이벤트 추가하는 곳
            window.location.reload()
        }
}
</script>

<!-- banner -->
<div class="banner"></div>
<!-- //banner -->
<main>
    <div class="row row-cols-1 row-cols-md-3 g-4 p-5 ">
        
        {% for post in posts %}
        <div class="col" style="height: 24rem;">
            <a href="{% url 'blog:blog_detail' post.pk %}">
                <div class="card h-100">
                {% if post.thumbnail_image %}
                <img src="{{ post.thumbnail_image.url }}" class="card-img-top" alt="..." width="320" height="167" style="object-fit: cover;">
                {% else %}
                <img src="{% static './images/default_logo.png' %}" class="card-img-top" alt="..." width="320" height="167" style="object-fit: cover;">
                {% endif %}
                <div class="d-flex card-body flex-column">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text fs-6 mb-auto">{{ post.body|striptags|safe }}</p>
                    <div class="fs-6 pt-4">{{ post.created_at|date:"Y년 m월 d일 G:i" }}</div>
                </div>
                <div class="d-flex card-footer justify-content-between">
                    <small class="text-muted fs-6">
                        <span>Posted by</span>
                        <span style="color: black;"><b><i>{{ post.author.nickname }}</i></b></span>
                    </small>
                    <small class="d-flex text-muted fs-6 flex-row gap-3">
                        <div class="d-flex align-items-center gap-2">
                            <img src="{% static './assets/view_icon.svg' %}">
                            <span>{{ post.views_count }}</span>
                        </div>
                        <div class="d-flex align-items-center gap-2">
                            <img src="{% static './assets/comment_icon.svg' %}">
                            <span>{{ post.reply_count }}</span>
                        </div>
                    </small>
                    
                </div>
                </div>
            </a>
        </div>
        {% endfor %}

    </div>
</main>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" style="border-radius: 0.8rem 0rem 0rem 0.8rem;">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true" style="border-radius: 0.8rem 0rem 0rem 0.8rem;">Previous</a>
    </li>
    {% endif %}

    {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="#" style="border-radius: 0rem;">{{ i }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{i}}" style="border-radius: 0rem;">{{ i }}</a></li>
        {% endif %}
        
    {% endfor %}
    

    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{page_obj.next_page_number}}" style="border-radius: 0rem 0.8rem 0.8rem 0rem;">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" style="border-radius: 0rem 0.8rem 0.8rem 0rem;">Next</a>
    </li>
    {% endif %}
    </ul>
</nav>
{% endblock %}

templates/blog/post_search.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block contents %}

<script type="text/javascript">

    window.onload = () => {
        const searchParams=new URLSearchParams(location.search)
        console.log(searchParams)
        const sortType = document.getElementById('sort_type')
        for (i = 0; i < sortType.options.length; i++){
            if (searchParams.get('sort') == sortType.options[i].value){
                sortType.value=sortType.options[i].value
            }
        }
    }
</script>

<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col col-md-7 g-5 pt-3">
                <form action="" method="get">
                    {% csrf_token %}
                    <p>
                        <input type="search" placeholder="검색어를 입력하세요" name="q"  value="{{ request.GET.q }}" class="form-control rounded-pill" style="height: 3rem; padding: 25px 30px 25px 30px;">
                    </p>
                    <p>
                        <select name="sort" class="form-select rounded-pill" style="padding: 5px 30px 5px 30px;" id="sort_type">
                            <option value="latest" selected>최신순</option>
                            <option value="past">과거순</option>
                        </select>
                    </p>
                    <div class="mt-4">
                        <button type="submit" class="container-fluid btn btn-secondary align-items-right">검색</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="row row-cols-1 row-cols-md-1 g-4 p-5 justify-content-center">
            {% for post in posts %}
            <div class="col col-md-7 mb-5" style="height: 26rem;">
                <a href="{% url 'blog:blog_detail' post.pk %}">
                    <div class="card h-100">
                    {% if post.thumbnail_image %}
                        <img src="{{ post.thumbnail_image.url }}" class="card-img-top" alt="..." width="320" height="167" style="object-fit: cover;">
                    {% else %}
                        <img src="{% static './images/default_logo.png' %}" class="card-img-top" alt="..." width="320" height="167" style="object-fit: cover;">
                    {% endif %}
                    <div class="d-flex card-body flex-column">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text fs-6 mb-auto">{{ post.body|striptags|safe }}</p>
                        <div class="fs-6 pt-4">{{ post.created_at|date:"Y년 m월 d일 G:i" }}</div>
                    </div>
                    <div class="d-flex card-footer justify-content-between">
                        <small class="text-muted fs-6">
                            <span>Posted by</span>
                            <span style="color: black;"><b><i>{{ post.author.nickname }}</i></b></span>
                        </small>
                        <small class="d-flex text-muted fs-6 flex-row gap-3">
                            <div class="d-flex align-items-center gap-2">
                                <img src="{% static './assets/view_icon.svg' %}">
                                <span>{{ post.views_count }}</span>
                            </div>
                            <div class="d-flex align-items-center gap-2">
                                <img src="{% static './assets/comment_icon.svg' %}">
                                <span>{{ post.reply_count }}</span>
                            </div>
                        </small>
                    </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock %}