blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('write/', views.blog_write, name='blog_write'),
    path('write/comment/<int:pk>/', views.blog_comment, name='blog_comment'),
    path('write/comment/reply/<int:pk>/', views.blog_comment_reply, name='blog_comment_reply'),
    path('delete/comment/<int:pk>/', views.blog_delete_comment, name='blog_delete_comment'),
    path('delete/recomment/<int:pk>/', views.blog_delete_recomment, name='blog_delete_recomment'),
    path('edit/<int:pk>/', views.blog_edit, name='blog_edit'),
    path('delete/<int:pk>/', views.blog_delete, name='blog_delete'),
    path('search/', views.blog_search, name='blog_search')
]

travelog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   # path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.user_profile, name='user_profile'),
    path('delete/<int:pk>/', views.user_delete, name='user_delete'),
    path('profile/update/<int:pk>/', views.user_update, name='user_profile_update'),
    path('profile/change-password/', views.user_change_password, name='user_change_password'),
    path('profile/password_change_done', views.user_change_password_done, name='user_password_change_done')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko-KR">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Travelog</title>

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

		<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >

		<link rel="stylesheet" href="{% static './css/banner.css' %}" />
		<link rel="stylesheet" href="{% static './css/global.css' %}" />
		<link rel="stylesheet" href="{% static './css/main.css' %}" />

		<style rel="stylesheet">
			.card-text{
				font-size:20px;
				overflow: hidden;
				text-overflow: ellipsis;
				overflow-wrap: break-word;
				word-wrap: break-word;
				word-break: normal;
				hyphens: auto;
				display: -webkit-box;
				-webkit-line-clamp: 3;
				-webkit-box-orient: vertical;
			}

			.card{
				overflow: hidden;
				background: var(--gray-background-light);
			}

			.github-image {
				width: 24px;
				height: 24px;
			}

			#wrap {
				min-height: calc(100vh - 4rem);
			}

			footer {
				height: 4rem;
			}

		</style>
	</head>
	<body>
		<!-- header -->
		<header>
			<nav class="navbar navbar-expand-lg navbar-white bg-white p-3">
				<div class="container-fluid">
					<a class="navbar-brand" href="{% url 'blog:blog_list' %}">
						<img src="{% static './assets/travelog_logo.svg' %}">
					</a>
					
					<div class="row align-self-center">
						<div class="col col-md-auto align-self-center">
							<a href="{% url 'blog:blog_search' %}" class="btn btn-outline-secondary">
								<div class="row justify-content-center">
									<div class="col">
										<div class="d-flex align-items-center gap-2">
											<img src="{% static './assets/search.svg' %}" alt="">
											<span>검색</span>
										</div>
									</div>
								</div>
							</a>
						</div>
						{% if user.is_authenticated %}
						<div class="col col-md-auto align-self-center">
							<a href="{% url 'user:user_profile' %}" class="btn btn-outline-secondary">
								<div class="row justify-content-center">
									<div class="col">
										<div class="d-flex align-items-center gap-2">
											<img src="{% static './assets/my_info.svg' %}" alt="">
											<span>내 정보</span>
										</div>
									</div>
								</div>
							</a>
						</div>
						<div class="col col-md-auto align-self-center">
							<a href="{% url 'blog:blog_write' %}" class="btn btn-primary" style="background-color: rgb(55, 170, 236);">
								<div class="row justify-content-center">
									<div class="col">
										<div class="d-flex align-items-center gap-2">
											<img src="{% static './assets/icon-modify-white.svg' %}" alt="">
											<span>포스팅</span>
										</div>
									</div>
								</div>
							</a>
						</div>
						<div class="col col-md-auto align-self-center">
							<a href="{% url 'user:user_logout' %}" class="btn">
								<div class="row justify-content-center">
									<div class="col">
										<div class="d-flex align-items-center gap-2">
											<img src="{% static './assets/base_logout.svg' %}" alt="">
											<span>로그아웃</span>
										</div>
									</div>
								</div>
							</a>
						</div>
						{% else %}
						<div class="col col-md-auto align-self-center">
							<a href="{% url 'user:user_login' %}" class="btn">
								<div class="row justify-content-center">
									<div class="col">
										<div class="d-flex align-items-center gap-2">
											<img src="{% static './assets/base_login.svg' %}" width="16px" height="16px" alt="">
											<span>로그인</span>
										</div>
									</div>
								</div>
							</a>
						</div>
						{% endif %}
					</div>
				</div>
			</nav>
		</header>

		<div id="wrap">
			{% block contents %}
			{% endblock %}
		</div>
		
		<!-- footer -->
		<footer class="footer mt-auto p-3 bg-white" style="bottom: 0;">
			<div class="d-flex container-fluid justify-content-between">
				<span class="text-muted fs-5">Copyright 2023. 남영훈 all rights reserved.</span>
				<div class="row">
					<div class="col">
						<a href="https://github.com/Nam-Younghoon" target="_blank">
							<img src="{% static './assets/github-mark.svg' %}" class="github-image">
						</a>
					</div>
					<div class="col">
						<a href="https://www.instagram.com/n.y.hoon/" target="_blank">
							<img src="{% static './assets/instagram-icon.svg' %}" class="github-image">
						</a>
					</div>
					<div class="col">
						<a href="https://velog.io/@huny3410" target="_blank">
							<img src="{% static './assets/velog.svg' %}" class="github-image">
						</a>
					</div>
				</div>
			</div>
		</footer>
		<!-- //footer -->
	</body>
</html>