blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('write/', views.blog_write, name='blog_write'),
    path('write/comment/<int:pk>/', views.blog_comment, name='blog_comment'),
    path('write/comment/reply/<int:pk>/', views.blog_comment_reply, name='blog_comment_reply'),
    path('delete/comment/<int:pk>/', views.blog_delete_comment, name='blog_delete_comment'),
    path('delete/recomment/<int:pk>/', views.blog_delete_recomment, name='blog_delete_recomment'),
    path('edit/<int:pk>/', views.blog_edit, name='blog_edit'),
    path('delete/<int:pk>/', views.blog_delete, name='blog_delete'),
    path('search/', views.blog_search, name='blog_search')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

travelog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   # path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.user_profile, name='user_profile'),
    path('delete/<int:pk>/', views.user_delete, name='user_delete'),
    path('profile/update/<int:pk>/', views.user_update, name='user_profile_update'),
    path('profile/change-password/', views.user_change_password, name='user_change_password'),
    path('profile/password_change_done', views.user_change_password_done, name='user_password_change_done')
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    nickname = models.CharField(verbose_name="닉네임", max_length=50, unique=True, help_text='닉네임은 고유합니다!')
    email = models.EmailField(verbose_name="이메일", unique=True)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, password_validation
from django.utils.translation import gettext_lazy as _

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    nickname = forms.CharField(
        label='닉네임',
        help_text='닉네임은 중복될 수 없습니다',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    
    email = forms.EmailField(
        label='이메일',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    password1 = forms.CharField(
        label='비밀번호',
        help_text=password_validation.password_validators_help_text_html(),
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'nickname', 'email']


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['nickname', 'email']

        widgets = {
            'nickname': forms.TextInput(attrs={
                'class': 'col form-control',
                'style': 'margin-right: 1rem; margin-left: 1rem;'
            }),
            'email': forms.TextInput(attrs={
                'class': 'col form-control',
                'style': 'margin-right: 1rem; margin-left: 1rem;'
            }),
        }
        

user/views.py
from typing import Any
from django import http
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.views.generic import CreateView, TemplateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.views.generic import UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class UserRegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'user/register.html'
    success_url = reverse_lazy('user:user_login')

class UserLogoutView(LogoutView):
    next_page = 'home:home'

class UserLoginView(LoginView):
    template_name = 'user/login.html'
    redirect_authenticated_user = True
    next_page = 'blog:blog_list'

class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'user/profile.html'

class UserChangePasswordView(PasswordChangeView):
    template_name = 'user/password_change_form.html'
    success_url = reverse_lazy("user:user_password_change_done")

    

class UserPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'user/password_change_done.html'

    def get(self, request, *args, **kwargs):
        request.session.flush()
        logout(request)
        return super().get(request, *args, **kwargs)
    
class UserProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'user/update.html'
    form_class = CustomUserChangeForm
    model = get_user_model()
    success_url = reverse_lazy('user:user_profile')

    def test_func(self) -> bool | None:
        return self.get_object() == self.request.user
    
class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'user/user_confirm_delete.html'
    model = get_user_model()
    success_url = reverse_lazy('home:home')

    def test_func(self) -> bool | None:
        return self.get_object() == self.request.user






user_register = UserRegisterView.as_view()
user_logout = UserLogoutView.as_view()
user_login = UserLoginView.as_view()
user_profile = UserProfileView.as_view()
user_delete = UserDeleteView.as_view()
user_change_password = UserChangePasswordView.as_view()
user_change_password_done = UserPasswordChangeDoneView.as_view()
user_update = UserProfileUpdateView.as_view()

templates/user/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <style rel="stylesheet">
        @font-face {
            font-family: 'Pretendard-Regular';
            src: url('https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff') format('woff');
            font-weight: 400;
            font-style: normal;
        }

        @keyframes backgroundChange {
            0% {
                background-position: 0 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }
        
        body {
            font-family: Pretendard-Regular;
            background-size: 150% 150%;
            background-repeat: no-repeat;
            animation: backgroundChange 20s ease-in-out infinite;
            background-image: url('{% static 'images/main-bg-cloud.jpg' %}')
        }

        a {
            text-decoration-line: none;
        }
    </style>
</head>
<body>
    <div class="container-sm" style="height: 100vh; display: flex; flex-direction: column;justify-content: center;">
        <div class="row justify-content-center fs-1" style="height: 120px; color: wheat;">
            Travelog
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="mb-3">
                    <div class="row justify-content-center">
                        <div class="col col-md-6">
                            <div class="form-label">아이디</div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col col-md-6">
                            {{ form.username | add_class:'form-control' }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="mb-5">
                    <div class="row justify-content-center">
                        <div class="col col-md-6">
                            <div class="form-label">비밀번호</div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col col-md-6">
                            {{ form.password | add_class:'form-control' }}
                        </div>
                    </div>
                    {%  if form.errors  %}
                        {% for error in form.errors.as_data.values %}
                            {% for data in error.0 %}
                            <div class="row justify-content-center mt-3">
                                <div class="col col-md-6">
                                    <p style="color: rgb(253, 64, 64);">{{data}}</p>
                                </div>
                            </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col col-md-6">
                    <div class="d-grid">
                        <button type="submit" class="btn btn-secondary">로그인</button>
                    </div>
                </div>
            </div>
        </form>
        <div class="row justify-content-center mt-3 mb-5">
            <div class="col col-md-6">
                <div class="d-grid">
                    <a href="{% url 'home:home' %}">홈으로</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/user/password_change_done.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block contents %}
<div class="banner"></div>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col col-md-7 g-5 pt-3">
                <div class="card mb-5">
                    <div class="card-body">
                        <div class="card-title fs-2"><b>비밀번호 변경 완료</b></div>
                        <hr>
                        <div class="row align-items-center" style="margin-top: 2rem;">
                            <div class="col">
                                <p>{{ title }}</p>
                            </div>
                        </div>
                        <div class="row align-items-center" style="margin-top: 2rem;">
                            <div class="col card-link">
                                <a href="{% url 'blog:blog_list' %}" class="btn btn-outline-primary">홈으로</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

templates/user/password_change_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block contents %}
<div class="banner"></div>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col col-md-7 g-5 pt-3">
                <div class="card mb-5">
                    <div class="card-body">
                        <div class="card-title fs-2"><b>비밀번호 변경</b></div>
                        <hr>
                            <div class="row align-items-center" style="margin-top: 2rem;">
                                <div class="col-md-auto">기존 비밀번호 : </div>
                                {% render_field form.old_password class="col form-control" style="margin-right: 1rem; margin-left: 1rem;" %}
                            </div>
                            <div class="row align-items-center" style="margin-top: 1rem;">
                                <div class="col-md-auto">새 비밀번호 : </div>
                                {% render_field form.new_password1 class="col form-control" style="margin-right: 1rem; margin-left: 1rem;" %}
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    {{ form.new_password1.help_text }}
                                </div>
                            </div>
                            <div class="row align-items-center" style="margin-top: 1rem;">
                                <div class="col-md-auto">새 비밀번호 (확인) : </div>
                                {% render_field form.new_password2 class="col form-control" style="margin-right: 1rem; margin-left: 1rem;" %}
                            </div>
                            {%  if form.errors  %}
                                {% for error in form.errors.as_data.values %}
                                    {% for data in error.0 %}
                                        <div class="row mt-4">
                                            <div class="col">
                                                <div style="color: rgb(253, 64, 64);">{{data}}</div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                            <div class="row mt-4">
                                <div class="col text-end">
                                    <button type="submit" class="card-link btn btn-outline-secondary">변경하기</button>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

<!-- <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">변경하기</button>
</form> -->

templates/user/profile.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

<div class="banner"></div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col col-md-7 g-5 pt-3">
            <div class="card">
                <div class="card-body">
                    <div class="card-title fs-2"><b>회원정보</b></div>
                    <hr>
                    <div class="row align-items-center" style="margin-top: 2rem;">
                        <div class="col-md-auto">아이디 : </div>
                        <input class="col form-control" style="margin-right: 1rem; margin-left: 1rem;" value="{{ user.username }}" disabled></input>
                    </div>
                    <div class="row align-items-center" style="margin-top: 1rem;">
                        <div class="col-md-auto">닉네임 : </div>
                        <input class="col form-control" style="margin-right: 1rem; margin-left: 1rem;" value="{{ user.nickname }}" disabled></input>
                    </div>
                    <div class="row align-items-center" style="margin-top: 1rem;">
                        <div class="col-md-auto">이메일 : </div>
                        <input class="col form-control" style="margin-right: 1rem; margin-left: 1rem;" value="{{ user.email }}" disabled></input>
                    </div>
                    <div class="row mt-4">
                        <div class="col text-end">
                            <a href="{% url 'user:user_delete' user.pk %}" class="card-link btn btn-danger">회원 탈퇴</a>
                            <a href="{% url 'user:user_change_password' %}" class="card-link btn btn-outline-danger">비밀번호 변경</a>
                            <a href="{% url 'user:user_profile_update' user.pk %}" class="card-link btn btn-outline-secondary">수정</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/register.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <style rel="stylesheet">
        @font-face {
            font-family: 'Pretendard-Regular';
            src: url('https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff') format('woff');
            font-weight: 400;
            font-style: normal;
        }

        @keyframes backgroundChange {
            0% {
                background-position: 0 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }
        
        body {
            font-family: Pretendard-Regular;
            background-size: 150% 150%;
            background-repeat: no-repeat;
            animation: backgroundChange 20s ease-in-out infinite;
            background-image: url('{% static 'images/main-bg-cloud.jpg' %}')
        }
    </style>
</head>
<body>
    <div class="container-sm" style="height: 100%; display: flex; flex-direction: column;justify-content: center;">
        <div class="row justify-content-center fs-1 p-5" style="color: wheat;">
            Travelog
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="col mb-3">
                <div class="row justify-content-center">
                    <div class="col col-md-6">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                        {{ form.username.help_text }}
                        {% for error in form.username.errors %}
                            <div class="help-block" style="color: rgb(253, 64, 64);">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col mb-3">
                <div class="row justify-content-center">
                    <div class="col col-md-6">
                        {{ form.nickname.label_tag }}
                        {{ form.nickname }}
                        {{ form.nickname.help_text }}
                        {% for error in form.nickname.errors %}
                            <div class="help-block" style="color: rgb(253, 64, 64);">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col mb-3">
                <div class="row justify-content-center">
                    <div class="col col-md-6">
                        {{ form.email.label_tag }}
                        {{ form.email }}
                        {% for error in form.email.errors %}
                            <div class="help-block" style="color: rgb(253, 64, 64);">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col mb-3">
                <div class="row justify-content-center">
                    <div class="col col-md-6">
                        {{ form.password1.label_tag }}
                        {{ form.password1 }}
                        <div class="pt-2">{{ form.password1.help_text }}</span>
                        {% for error in form.password1.errors %}
                            <div class="help-block" style="color: rgb(253, 64, 64);">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col mb-3">
                <div class="row justify-content-center">
                    <div class="col col-md-6">
                        {{ form.password2.label_tag }}
                        {{ form.password2 }}
                        {% for error in form.password2.errors %}
                            <div class="help-block" style="color: rgb(253, 64, 64);">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="row justify-content-center mt-5 mb-2">
                <div class="col col-md-6">
                    <div class="d-grid">
                        <button type="submit" class="btn btn-secondary">회원가입</button>
                    </div>
                </div>
            </div>
        </form>
        <div class="row justify-content-center mt-3 mb-5">
            <div class="col col-md-6">
                <div class="d-grid">
                    <a href="{% url 'home:home' %}" style="text-decoration: none;">홈으로</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/user/update.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
<div class="banner"></div>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col col-md-7 g-5 pt-3">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title fs-2"><b>회원정보 수정</b></div>
                        <hr>
                            <div class="row align-items-center" style="margin-top: 2rem;">
                                <div class="col-md-auto">닉네임 : </div>
                                {{ form.nickname }}
                            </div>
                            <div class="row align-items-center" style="margin-top: 1rem;">
                                <div class="col-md-auto">이메일 : </div>
                                {{ form.email }}
                            </div>
                            <div class="row mt-4">
                                <div class="col text-end">
                                    <button type="submit" class="card-link btn btn-outline-secondary">변경하기</button>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

templates/user/user_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

<div class="banner"></div>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col col-md-4 g-5 pt-3">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title fs-2"><b>회원탈퇴</b></div>
                        <hr>
                        <p>정말로 탈퇴하시겠어요?</p>
                        <div class="row mt-4 text-end">
                            <div class="col g-4">
                                <button type="submit" class="btn btn-danger">네</button>
                                <a href="{% url 'user:user_profile' %}" class="btn btn-outline-secondary ms-2">아니요</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}